In [1]:
import numpy as np
import dill

In [2]:
with open('dynamics.pkl', 'rb') as f:
    dynamics = dill.load(f)

with open('position.pkl', 'rb') as f:
    position = dill.load(f)

with open('velocity.pkl', 'rb') as f:
    velocity = dill.load(f)

In [3]:
y = np.zeros(6)
u = np.zeros(3)
u[1] = np.deg2rad(30.)

rho = np.array([0.5, 0.5, 0.5])
m = np.array([250., 25., 25.])
I = np.array([25., 2.5, 2.5])
b = np.zeros(3)

print(dynamics(y, u, rho, m, I, b))
print(position(y, rho))
print(velocity(y, rho))

[[-0.02223101]
 [ 0.05148234]
 [-0.04680213]]
(array([[0],
       [0]]), array([[1.],
       [0.]]), array([[2.],
       [0.]]))
(array([[0],
       [0]]), array([[-0.],
       [ 0.]]), array([[0.],
       [0.]]))
