In [1]:
import numpy as np
from remi.dynamics import forward_dynamics, inverse_dynamics
from remi.clik_functions import calc_clik_params
from remi.kinematics import (calc_critical_positions,
                             calc_capture_point_position,
                             calc_end_effector_position,
                             calc_obstacle_point_positions,
                             calc_critical_velocities,
                             calc_capture_point_velocity,
                             calc_end_effector_velocity,
                             calc_obstacle_point_velocities,
                             calc_capture_point_acceleration,
                             calc_J,
                             calc_J_dot)

In [2]:
y = np.zeros(8)
u = np.zeros(4)
u[1] = np.deg2rad(30.)

r_s = np.array([-1.5, 0.])
r_t = np.array([1.5, 0.])

rho = np.array([0.5, 0.5, 0.5, 0.5])
m = np.array([250., 25., 25., 180.])
I = np.array([25., 2.5, 2.5, 18.])
d = np.zeros(4)

p = np.ones(3)
w = np.ones(6)
q_bar = np.zeros(3)
q_max = np.ones(3)*np.pi
q_min = np.ones(3)*-np.pi

In [3]:
calc_critical_positions(y, rho, r_s)

(array([[0.],
        [0.]]),
 array([[0.5],
        [0. ]]),
 array([[1.],
        [0.]]))

In [4]:
calc_clik_params(y, rho, r_s, r_t, p, q_bar, q_max, q_min, w)

(array([[41.91, 29.7 ,  5.28]]), array([[0., 0., 0.]]))

In [5]:
forward_dynamics(y, u, r_s, r_t, rho, m, I, d)

array([-0.02223101,  0.05148234, -0.04680213,  0.        ])

In [6]:
inverse_dynamics(y, np.ones(4), r_s, r_t, rho, m, I, d)

array([262.5 , 171.25,  52.5 ,  18.  ])