In [1]:
import numpy as np
from remi import (load_ee_func,
                  load_Je_func,
                  load_position_func,
                  load_velocity_func)

In [2]:
r_s = np.array([-1.5, 0.])              # central satellite position
r_t = np.array([1.5, 0.])               # central target position
rho = np.array([0.5, 0.5, 0.5, 0.5])    # dimension array

y0 = np.array([0.,                      # theta_s
               np.deg2rad(30.),         # theta_1
               0.,                      # theta_2
               0.,                      # theta_t
               np.deg2rad(5.),          # theta_dot_s
               np.deg2rad(10.),         # theta_dot_1
               0.,                      # theta_dot_2
               np.deg2rad(-5.)          # theta_dot_t
               ])                       # initial conditions

In [3]:
ee = load_ee_func()
Je = load_Je_func()
pos = load_position_func()
vel = load_velocity_func()

### Position Function
**Input**: state, central position of satellite, central position of target, dimension array (rho) \
**Output**: central position of link 1, central position of link 2, capture point position

**NOTE**: `r_s` and `r_t` need to be arrays of shape (2, 1) and not just (2,)

In [4]:
pos(y0, r_s[:, None], r_t[:, None], rho)

(array([[-0.5669873,  0.25     ]]),
 array([[0.29903811, 0.75      ]]),
 array([[1.5, 0.5]]))

### Velocity Function
**Input**: state, central position of satellite, central position of target, dimension array (rho) \
**Output**: velocity of link 1, velocity of link2, capture point velocity

**NOTE**: `r_s` and `r_t` need to be arrays of shape (2, 1) and not just (2,)

In [5]:
vel(y0, r_s[:, None], r_t[:, None], rho)

(array([[-0.06544985,  0.15699569]]),
 array([[-0.19634954,  0.38372061]]),
 array([[0.04363323, 0.        ]]))

### End Effector Function
**Input**: state, central position of the satellite, dimension array (rho) \
**Output**: end effector position

**NOTE**: `r_s` must be of shape (2, 1) and not just (2,)

In [6]:
ee(y0, r_s[:, None], rho)

array([[[0.73205081],
        [1.        ]]])

### Jacobian of End Effector Function
**Input**: state, dimension array (rho) \
**Output**: Jacobian of end effector

In [7]:
J = Je(y0, rho)
print(J)

[[-1.         -1.         -0.5       ]
 [ 2.23205081  1.73205081  0.8660254 ]]


### Psuedo-Inverse of Jacobian

**NOTE**: Having all 0s (and 180s) could yield non-singular Jacobian psuedo-inverse

In [8]:
J.T@np.linalg.inv(J@J.T)

array([[ 3.46410162,  2.        ],
       [-3.57128129, -1.6       ],
       [-1.78564065, -0.8       ]])